### PR TITLE
Fix rest_framework import sentences

### PR DESCRIPTION
**Pull request by bameda**

### CODE REVIEW

**Comment by astagi** [comment]
Hey @bameda thanks :) just a question, why do you keep rest framework classes into taiga as of now?

**Comment by bameda** [comment]
We need to make all string translateables. DRF 3.1 support. i18n but we can't update to this version because we use a very customized DRF 2.x version. We have customized practically everything except serializers, parsers and renderers.

In the future, we want to refactor this part because DRF isn't adapts very well to our needs.

**Comment by astagi** [comment]
that's fine! thank you for your clarification :)

**Comment by bameda** [comment]
Your comments and suggestions are always welcome

**Comment by astagi** [comment]
ok :) I'll take a deeper look at the backend code!

**Pull request merged**
