### PR TITLE
Feature/configurable notifications

### PR DESCRIPTION
**Pull request by astagi**

### CODE REVIEW

**Comment by astagi** [comment]
@Xaviju I think that some better style is needed :smile:

**Comment by Xaviju** [comment]
@astagi  Nice!! I'll be happy to review the styles :)

**Comment by astagi** [comment]
Thanks @Xaviju I'll merge this PR when styles are available :)

**Comment by Xaviju** [comment]
I've just seen it! Looks nice, I'll try to polish it tomorrow.

**Comment by Xaviju** [comment]
@astagi need to understand well the UX.
When a user enables "Enable HipChat notifications" then all the notification options are available and change the notification messages but if this button its not checked it makes no sense to show all the options, right?

**Comment by astagi** [comment]
@Xaviju with "HipChat notifications" I mean to set an option in the HipChat API call, just to make the "blimp" sound in HipChat or not :) it's not related with notification filters..

**Comment by Xaviju** [comment]
@astagi OK, that was confusing, do you mind if I change it to "Enable notifications on HipChat?"

**Comment by astagi** [comment]
it's confusing :D yes, no problem @Xaviju  :)

**Comment by Xaviju** [comment]
Ok some minor fixes and will be ready!

**Comment by astagi** [comment]
fantastic thanks :+1: :smile:

**Comment by Xaviju** [comment]
Please pull from taiga master before testing, but should be already fixed :dancer:

**Comment by astagi** [comment]
that's great @Xaviju thanks :) just a little thing, I think there are some problem on the TEST button, I attach a screenshot
screen shot 2015-09-15 at 16 52 09

**Comment by Xaviju** [comment]
@astagi Did you pull the Taiga CSS on master and removed the caché? Your screenshot seems to be outdated. Ill check it again tomorrow. :open_mouth:

**Comment by astagi** [comment]
ok, thanks :smile: yes I did, I also used "gulp clear" and deleted browser's cache..

**Comment by Xaviju** [comment]
Ok so its ready to merge for me

**Comment by astagi** [comment]
@Xaviju I forgot to mention that the problem still exists for me :) anyway yes we can merge this PR for now..

**Comment by Xaviju** [comment]
Mmmm, I tried it again today and seem to work fine. Could you check if you have this commit in `taiga-front` in `master`?  
https://github.com/taigaio/taiga-front/commit/a48a8d77c766550a95ba364e6eaeff706eaf5901

This is my local screnshot: http://www.awesomescreenshot.com/image/578010/ee48837c5924537f80cb5dfb0807825d

**Comment by bameda** [comment]
In my machine works too ;-)

image

**Comment by astagi** [comment]
ok it looks like I am having some problem with my chrome version :P I tried it in an incognito window and it works! :smile: sorry for that!

**Pull request merged**
